# Generated by Django 6.0 on 2025-12-26 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Vaccination', 'Vaccination'), ('Vet Visit', 'Vet Visit'), ('Injury', 'Injury'), ('Checkup', 'Checkup'), ('Other', 'Other')], max_length=50)),
                ('event_date', models.DateField()),
                ('description', models.TextField()),
                ('veterinarian', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='dashboard.pet')),
            ],
        ),
    ]
