"""
Django settings for pethealthtracker project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1%e07e2+67gbce$d1!^*(ihqw8-y50mr(b3x6cvof7rl+x=0)1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'home',   #homeapp
    'dashboard', #dashboardapp
    
   
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pethealthtracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],#template folder name added
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pethealthtracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database configuration using MySQL
DATABASES = {
    'default': {
        # Specifies MySQL as the database engine
        'ENGINE': 'django.db.backends.mysql',  # Use MySQL for backend

        # Name of the database to be used
        # This database must be created manually in MySQL
        'NAME': 'dashboard_pet',

        # Database username
        'USER': 'root',

        # Database password
        'PASSWORD': 'admin',

        # Database server address
        'HOST': 'localhost',

        # Port number on which MySQL server is running
        'PORT': '3306',
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


# URL prefix used when referring to static files in templates
# Example: <link rel="stylesheet" href="{% static 'css/style.css' %}">
STATIC_URL = 'static/'

# List of directories where Django will search for static files
# This is mainly used during development
STATICFILES_DIRS = [
    BASE_DIR / 'static',   # Points to the global "static" folder in the project root
]



# redirecting linking urls:

# URL where unauthenticated users are redirected
# This is triggered by @login_required decorator
LOGIN_URL = '/login/'

# URL where users are redirected after successful login
# Used by Django's authentication system
LOGIN_REDIRECT_URL = '/dashboard/'

# URL where users are redirected after changing their password
# Improves user experience by returning them to profile page
PASSWORD_CHANGE_REDIRECT_URL = "/dashboard/profile/"

